name: full_koll
description: "\"Full Koll is your ultimate personal finance companion, elegantly consolidating receipts, gift cards, budgets, expense splitting, and subscriptions into one intuitive app, empowering you to manage your money with clarity and control.\""
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  supabase_flutter: ^2.4.0
  pdf: ^3.0.0
  csv: ^6.0.0
  share_plus: ^12.0.0
  crypto: ^3.0.0
  permission_handler: ^12.0.0
  qr_code_dart_scan: 0.11.5
  file_picker: '>=8.1.2'
  path_provider: ^2.0.0
  sembast_web: ^2.0.0
  sembast: ^3.0.0
  sqflite_common_ffi_web: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.0.0
  provider: ^6.0.0
  sqflite: ^2.0.0
  path: ^1.0.0
  shared_preferences: ^2.0.0
  flutter_secure_storage: ^9.2.4
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  uuid: ^4.3.3
  image_picker: '>=1.1.2'
  local_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/app/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app/app_icon.svg
  remove_alpha_ios: true
